# Generated by Django 4.2.7 on 2023-12-04 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Factory', 'Завод'), ('Retail', 'Розничная сеть'), ('Entrepreneur', 'Индивидуальный предприниматель')], max_length=100, verbose_name='тип сети')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица/проспект')),
                ('house_number', models.CharField(max_length=10, verbose_name='номер дома')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='модель')),
                ('release_date', models.DateField(verbose_name='дата релиза')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='долг поставщику')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='main.network', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
